name: Rust

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - uses: ncipollo/release-action@v1
      name: Release with tag name
      with:
        artifacts: "target/release/tokengen-cert"
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: ncipollo/release-action@v1
      name: Release as latest
      with:
        artifacts: "target/release/tokengen-cert"
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Latest
        tag: latest
